//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bang_Gia
    {
        public int STT { get; set; }
        public Nullable<int> don_gia_xe_bus { get; set; }
        public Nullable<int> gia_ve_1_ngay_trong_tuan { get; set; }
        public Nullable<int> gia_ve_1_ngay_cuoi_tuan { get; set; }
    }
}
