//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyen_tau_xe_ghe_ga_tram
    {
        public string Ma_tuyen { get; set; }
        public byte STT_chuyen { get; set; }
        public string Ma_ga_tram { get; set; }
        public Nullable<byte> STT_tram { get; set; }
        public Nullable<System.TimeSpan> gio_ghe { get; set; }
        public Nullable<System.TimeSpan> gio_di { get; set; }
    
        public virtual Chuyen_tau_xe Chuyen_tau_xe { get; set; }
        public virtual Ga_Tram Ga_Tram { get; set; }
    }
}
