//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chuyen_tau_xe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chuyen_tau_xe()
        {
            this.Chuyen_tau_xe_ghe_ga_tram = new HashSet<Chuyen_tau_xe_ghe_ga_tram>();
        }
    
        public string Ma_tuyen { get; set; }
        public byte STT { get; set; }
    
        public virtual Tuyen_tau_xe Tuyen_tau_xe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyen_tau_xe_ghe_ga_tram> Chuyen_tau_xe_ghe_ga_tram { get; set; }
    }
}
