//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doan_duong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doan_duong()
        {
            this.Ga_Tram = new HashSet<Ga_Tram>();
        }
    
        public string Ma_giao_lo_1 { get; set; }
        public string Ma_giao_lo_2 { get; set; }
        public string Ma_con_duong { get; set; }
        public Nullable<int> STT { get; set; }
    
        public virtual Con_duong Con_duong { get; set; }
        public virtual Giao_lo Giao_lo { get; set; }
        public virtual Giao_lo Giao_lo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ga_Tram> Ga_Tram { get; set; }
    }
}
