//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ga_Tram_Lam_Viec
    {
        public string Ma_nhan_vien { get; set; }
        public string Ma_ga_tram { get; set; }
    
        public virtual Ga_Tram Ga_Tram { get; set; }
        public virtual Nhan_Vien Nhan_Vien { get; set; }
    }
}
