//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ga_Tram
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ga_Tram()
        {
            this.Chuyen_tau_xe_ghe_ga_tram = new HashSet<Chuyen_tau_xe_ghe_ga_tram>();
            this.Ga_Tram_Lam_Viec = new HashSet<Ga_Tram_Lam_Viec>();
            this.HD_ve_ngay = new HashSet<HD_ve_ngay>();
            this.HD_ve_ngay1 = new HashSet<HD_ve_ngay>();
            this.HD_ve_thang = new HashSet<HD_ve_thang>();
            this.HD_ve_thang1 = new HashSet<HD_ve_thang>();
            this.Ve_le = new HashSet<Ve_le>();
            this.Ve_le1 = new HashSet<Ve_le>();
            this.Ve_thang = new HashSet<Ve_thang>();
            this.Ve_thang1 = new HashSet<Ve_thang>();
        }
    
        public string Ma_ga_tram { get; set; }
        public string dia_chi { get; set; }
        public string ten { get; set; }
        public Nullable<byte> Ga_Tram1 { get; set; }
        public string ma_giao_lo_1 { get; set; }
        public string ma_giao_lo_2 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chuyen_tau_xe_ghe_ga_tram> Chuyen_tau_xe_ghe_ga_tram { get; set; }
        public virtual Doan_duong Doan_duong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ga_Tram_Lam_Viec> Ga_Tram_Lam_Viec { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_ngay> HD_ve_ngay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_ngay> HD_ve_ngay1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_thang> HD_ve_thang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_thang> HD_ve_thang1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve_le> Ve_le { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve_le> Ve_le1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve_thang> Ve_thang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve_thang> Ve_thang1 { get; set; }
    }
}
