//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hanh_Khach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hanh_Khach()
        {
            this.The_Tu = new HashSet<The_Tu>();
            this.Ves = new HashSet<Ve>();
        }
    
        public string Ma_hanh_khach { get; set; }
        public string ten { get; set; }
        public string CMND_CCCD { get; set; }
        public string nghe_nghiep { get; set; }
        public string dien_thoai { get; set; }
        public string gioi_tinh { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<The_Tu> The_Tu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ve> Ves { get; set; }
    }
}
