//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLPTCCEntities3 : DbContext
    {
        public QLPTCCEntities3()
            : base("name=QLPTCCEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bang_Gia> Bang_Gia { get; set; }
        public virtual DbSet<Chuyen_tau_xe> Chuyen_tau_xe { get; set; }
        public virtual DbSet<Chuyen_tau_xe_ghe_ga_tram> Chuyen_tau_xe_ghe_ga_tram { get; set; }
        public virtual DbSet<Con_duong> Con_duong { get; set; }
        public virtual DbSet<Doan_duong> Doan_duong { get; set; }
        public virtual DbSet<Ga_Tram> Ga_Tram { get; set; }
        public virtual DbSet<Ga_Tram_Lam_Viec> Ga_Tram_Lam_Viec { get; set; }
        public virtual DbSet<Giao_lo> Giao_lo { get; set; }
        public virtual DbSet<Hanh_Khach> Hanh_Khach { get; set; }
        public virtual DbSet<HD_ve_ngay> HD_ve_ngay { get; set; }
        public virtual DbSet<HD_ve_thang> HD_ve_thang { get; set; }
        public virtual DbSet<Nhan_Vien> Nhan_Vien { get; set; }
        public virtual DbSet<The_Tu> The_Tu { get; set; }
        public virtual DbSet<Tuyen_tau_dien> Tuyen_tau_dien { get; set; }
        public virtual DbSet<Tuyen_tau_xe> Tuyen_tau_xe { get; set; }
        public virtual DbSet<Tuyen_xe_bus> Tuyen_xe_bus { get; set; }
        public virtual DbSet<Ve> Ves { get; set; }
        public virtual DbSet<Ve_1_ngay> Ve_1_ngay { get; set; }
        public virtual DbSet<Ve_le> Ve_le { get; set; }
        public virtual DbSet<Ve_thang> Ve_thang { get; set; }
    
        [DbFunction("QLPTCCEntities3", "Thong_ke_so_luot_nguoi")]
        public virtual IQueryable<Thong_ke_so_luot_nguoi_Result> Thong_ke_so_luot_nguoi(string matuyen, Nullable<System.DateTime> tungay, Nullable<System.DateTime> denngay)
        {
            var matuyenParameter = matuyen != null ?
                new ObjectParameter("matuyen", matuyen) :
                new ObjectParameter("matuyen", typeof(string));
    
            var tungayParameter = tungay.HasValue ?
                new ObjectParameter("tungay", tungay) :
                new ObjectParameter("tungay", typeof(System.DateTime));
    
            var denngayParameter = denngay.HasValue ?
                new ObjectParameter("denngay", denngay) :
                new ObjectParameter("denngay", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<Thong_ke_so_luot_nguoi_Result>("[QLPTCCEntities3].[Thong_ke_so_luot_nguoi](@matuyen, @tungay, @denngay)", matuyenParameter, tungayParameter, denngayParameter);
        }
    
        public virtual ObjectResult<LoTrinhTuyenXeTau_Result> LoTrinhTuyenXeTau(string matuyen)
        {
            var matuyenParameter = matuyen != null ?
                new ObjectParameter("matuyen", matuyen) :
                new ObjectParameter("matuyen", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LoTrinhTuyenXeTau_Result>("LoTrinhTuyenXeTau", matuyenParameter);
        }
    }
}
