//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nhan_Vien
    {
        public string Ma_nhan_vien { get; set; }
        public string ten { get; set; }
        public string loai_cong_viec { get; set; }
        public Nullable<System.DateTime> ngay_sinh { get; set; }
        public string email { get; set; }
        public string gioi_tinh { get; set; }
        public string dien_thoai_di_dong { get; set; }
        public string dien_thoai_noi_bo { get; set; }
    
        public virtual Ga_Tram_Lam_Viec Ga_Tram_Lam_Viec { get; set; }
    }
}
