//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyen_tau_dien
    {
        public string Ma_tuyen_tau { get; set; }
        public string Ten_tuyen_tau { get; set; }
        public Nullable<int> Don_gia { get; set; }
        public string Ma_tuyen_tau_dien { get; set; }
    
        public virtual Tuyen_tau_xe Tuyen_tau_xe { get; set; }
    }
}
