//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuyen_xe_bus
    {
        public int No { get; set; }
        public string Ma_tuyen_xe_bus { get; set; }
    
        public virtual Tuyen_tau_xe Tuyen_tau_xe { get; set; }
    }
}
