//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ve()
        {
            this.HD_ve_ngay = new HashSet<HD_ve_ngay>();
            this.HD_ve_thang = new HashSet<HD_ve_thang>();
        }
    
        public string Ma_ve { get; set; }
        public byte Loai_ve { get; set; }
        public Nullable<System.DateTime> Ngay_gio_mua { get; set; }
        public Nullable<int> Gia_ve { get; set; }
        public string Ma_khach_hang { get; set; }
    
        public virtual Hanh_Khach Hanh_Khach { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_ngay> HD_ve_ngay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HD_ve_thang> HD_ve_thang { get; set; }
        public virtual Ve_1_ngay Ve_1_ngay { get; set; }
        public virtual Ve_le Ve_le { get; set; }
        public virtual Ve_thang Ve_thang { get; set; }
    }
}
