//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportManagerment.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ve_1_ngay
    {
        public string Ma_ve { get; set; }
        public Nullable<System.DateTime> Ngay_su_dung { get; set; }
    
        public virtual Ve Ve { get; set; }
    }
}
